#!/bin/bash
mkdir /tmp/$$DC
#DVPATH=/opt/rtapps/dv
DVPATH=INSTALL_PATH
export DVPATH
if [ -d /usr/share/grace ]; then
    GRACE_HOME=/usr/share/grace
else
    GRACE_HOME=LOCAL_GRACE/grace
    LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${GRACE_HOME}/lib
    export LD_LIBRARY_PATH
fi
export GRACE_HOME
export LANG=C
PATH=${PATH}:${GRACE_HOME}/bin:`pwd`
$DVPATH/dc3 -s ${LIGONDSIP} -a $$ -b $DVPATH $*
/bin/rm -f -r /tmp/$$DC
