/*
** Generated by WorkShop Visual
*/
#ifndef _dc3_h
#define _dc3_h

#define XD_MOTIF











extern Cursor watch_cursor;

extern Widget tabBook;
extern Widget displayForm;
extern Widget inputForm;
extern Widget xmgraceToggle;
extern Widget xmgrToggle;
extern Widget newDisplayButton;
extern Widget plotDisplay;
extern Widget playbtn;
extern Widget startLong;
extern Widget connectButton;
extern Widget helpWin;
extern Widget errorDialog;
extern Widget errorDialogMessage;

extern Widget restoreWin;
extern Widget restorefile;

extern Widget saveWin;
extern Widget savefile;

extern Widget serverDialog;
extern Widget serverIpText;
extern Widget serverPortText;

extern Widget shell1;
extern Widget menuTop;
extern Widget mainTop;
extern Widget MainMenu;
extern Widget saveSets;
extern Widget restoreSets;
extern Widget reconfigure;
extern Widget reconnect;
extern Widget newConnection;
extern Widget exitall;
extern Widget signalTop;
extern Widget signalMenu;
extern Widget sigSel;
extern Widget playbackSel;
extern Widget framesTop;
extern Widget maketoc;
extern Widget opentoc;
extern Widget frameFile;
extern Widget helpTop;
extern Widget helpMenu;
extern Widget helpItem1;
extern Widget StatusForm;
extern Widget statusField;
extern Widget actionText;
extern Widget card;
extern Widget trigFrame;
extern Widget trigForm;
extern Widget trigLevelText;
extern Widget trigOn;
extern Widget aboveMenu;
extern Widget trigaboveMenu;
extern Widget above;
extern Widget below;
extern Widget trChMenu;
extern Widget trigMenu;
extern Widget trig1;
extern Widget trig2;
extern Widget trig3;
extern Widget trig4;
extern Widget trig5;
extern Widget trig6;
extern Widget trig7;
extern Widget trig8;
extern Widget trig9;
extern Widget trig10;
extern Widget trig11;
extern Widget trig12;
extern Widget trig13;
extern Widget trig14;
extern Widget trig15;
extern Widget trig16;
extern Widget midFrame;
extern Widget midForm;
extern Widget menuColor;
extern Widget menuColorText;
extern Widget colormenu;
extern Widget red;
extern Widget green;
extern Widget blue;
extern Widget yellow;
extern Widget brown;
extern Widget violet;
extern Widget cyan;
extern Widget magenta;
extern Widget orange;
extern Widget indigo;
extern Widget maroon;
extern Widget turqse;
extern Widget green4;
extern Widget alldef;
extern Widget xAxisFrame;
extern Widget menuDelay;
extern Widget menuDelayText;
extern Widget delayMenu;
extern Widget a0;
extern Widget a1;
extern Widget a2;
extern Widget a3;
extern Widget a4;
extern Widget a5;
extern Widget a6;
extern Widget a7;
extern Widget a8;
extern Widget a9;
extern Widget a10;
extern Widget a11;
extern Widget a12;
extern Widget a13;
extern Widget a14;
extern Widget a15;
extern Widget menuXScale;
extern Widget menuXScaleText;
extern Widget xAxisMenu;
extern Widget xAxisN16;
extern Widget xAxisN8;
extern Widget xAxisN4;
extern Widget xAxisN2;
extern Widget xAxis1;
extern Widget xAxis2;
extern Widget xAxis4;
extern Widget xAxis8;
extern Widget xAxis16;
extern Widget yAxisFrame;
extern Widget menuYScale;
extern Widget menuYScaleText;
extern Widget yScaleMenu;
extern Widget linearsel;
extern Widget expsel;
extern Widget logsel;
extern Widget lnsel;
extern Widget yscaleForm;
extern Widget yminLabel;
extern Widget yMinText;
extern Widget ymaxLabel;
extern Widget yMaxText;
extern Widget autoOn;
extern Widget unitOn;
extern Widget menuChan;
extern Widget menuChanText;
extern Widget chMenu;
extern Widget win1;
extern Widget win2;
extern Widget win3;
extern Widget win4;
extern Widget win5;
extern Widget win6;
extern Widget win7;
extern Widget win8;
extern Widget win9;
extern Widget win10;
extern Widget win11;
extern Widget win12;
extern Widget win13;
extern Widget win14;
extern Widget win15;
extern Widget win16;
extern Widget sigNamText;
extern Widget slotsFrame;
extern Widget ch1Select;
extern Widget ch2Select;
extern Widget ch3Select;
extern Widget ch4Select;
extern Widget ch5Select;
extern Widget ch6Select;
extern Widget ch7Select;
extern Widget ch8Select;
extern Widget ch9Select;
extern Widget ch10Select;
extern Widget ch11Select;
extern Widget ch12Select;
extern Widget ch13Select;
extern Widget ch14Select;
extern Widget ch15Select;
extern Widget ch16Select;
extern Widget modeForm;
extern Widget displayType;
extern Widget displayTypeText;
extern Widget opMenu;
extern Widget timebase;
extern Widget trmean;
extern Widget menuMode;
extern Widget menuModeText;
extern Widget modeMenu;
extern Widget stand;
extern Widget multi;
extern Widget menuRes;
extern Widget menuResText;
extern Widget reMenu;
extern Widget dr1;
extern Widget dr2;
extern Widget dr4;
extern Widget dr8;
extern Widget dr16;
extern Widget dr32;
extern Widget dr64;
extern Widget dr128;
extern Widget menuRate;
extern Widget menuRateText;
extern Widget rateMenu;
extern Widget freq1;
extern Widget freq2;
extern Widget freq4;
extern Widget freq8;
extern Widget freq16;
extern Widget buttonForm;
extern Widget stopbtn;
extern Widget playbtn;
extern Widget sigOn;
extern Widget filterOn;
extern Widget globalOn;

extern Widget Long;
extern Widget Longf;
extern Widget longCancel;
extern Widget longExecute;
extern Widget chlabel;
extern Widget lchann;
extern Widget longch;
extern Widget lch1;
extern Widget lch2;
extern Widget lch3;
extern Widget lch4;
extern Widget lch5;
extern Widget lch6;
extern Widget lch7;
extern Widget lch8;
extern Widget lch9;
extern Widget lch10;
extern Widget lch11;
extern Widget lch12;
extern Widget lch13;
extern Widget lch14;
extern Widget lch15;
extern Widget lch16;
extern Widget lformat;
extern Widget formlabel;
extern Widget ldate;
extern Widget ltotal;
extern Widget lmode;
extern Widget modelabel;
extern Widget lstand;
extern Widget lmult;
extern Widget multixmgr;
extern Widget lgrid;
extern Widget xgrid;
extern Widget ygrid;
extern Widget ltrend;
extern Widget lrms;
extern Widget lmax;
extern Widget lmin;
extern Widget ldec;
extern Widget decilabel;
extern Widget lfull;
extern Widget lsec;
extern Widget lmin1;
extern Widget lmin10;
extern Widget lhr;
extern Widget serverset;
extern Widget lserver;
extern Widget lframe;
extern Widget lIPtext;
extern Widget lPorttext;
extern Widget timeset;
extern Widget radiotime;
extern Widget lutc;
extern Widget lgps;
extern Widget timeNow;
extern Widget yrLab;
extern Widget moLab;
extern Widget dayLab;
extern Widget hrLab;
extern Widget minLab;
extern Widget secLab;
extern Widget playYr;
extern Widget playMo;
extern Widget playDa;
extern Widget playHr;
extern Widget playMn;
extern Widget playSc;
extern Widget refTimeDay;
extern Widget refTimeHr;
extern Widget refTimeMin;
extern Widget refTimeSec;
extern Widget durlab;
extern Widget gpslab;
extern Widget gpstime;
extern Widget gpsref;
extern Widget fbMenu;
extern Widget stoptime;
extern Widget starttime;
extern Widget autoset;
extern Widget styleMenu;
extern Widget style;
extern Widget stdefault;
extern Widget stline;
extern Widget stpoint;
extern Widget stopid;
extern Widget lidtext;
extern Widget longTrigExe;
extern Widget menuChtrig1;
extern Widget trigMenu1;
extern Widget menuAbove1;
extern Widget trigAboveLong1;
extern Widget above1;
extern Widget below1;
extern Widget equ1;
extern Widget trigLevelText1;
extern Widget manuChtrig2;
extern Widget trigMenu2;
extern Widget menuAbove2;
extern Widget trigAboveLong2;
extern Widget above2;
extern Widget below2;
extern Widget eqa2;
extern Widget trigLevelText2;
extern Widget menu_operation;
extern Widget trigandor;
extern Widget and;
extern Widget or;
extern Widget longbar;

extern Widget save_win;
extern Widget save_form;
extern Widget dirlist;
extern Widget filelist;
extern Widget savefile_bak;
extern Widget saveok;
extern Widget savecancel;
extern Widget savett;
extern Widget savexml;
extern Widget saveall;

extern Widget signal_Sel;
extern Widget sig_form;
extern Widget selsig;
extern Widget junk;
extern Widget chincr;
extern Widget chdecr;
extern Widget sigselect;
extern Widget selchan;
extern Widget sigcancel;
extern Widget fastslowch;
extern Widget sfast;
extern Widget sslow;
extern Widget sdmt;
extern Widget sobsole;
extern Widget tree;
extern Widget grouplist;
extern Widget signalListForm;
extern Widget siglist;
extern Widget slots;
extern Widget v1;
extern Widget v2;
extern Widget v3;
extern Widget v4;
extern Widget v5;
extern Widget v6;
extern Widget v7;
extern Widget v8;
extern Widget v9;
extern Widget v10;
extern Widget v11;
extern Widget v12;
extern Widget v13;
extern Widget v14;
extern Widget v15;
extern Widget v16;

extern Widget help_win;
extern Widget about_form;
extern Widget aboutlab;
extern Widget abouttext;
extern Widget close_hb;

extern Widget frame_win;
extern Widget framefile_form;
extern Widget dirlist1;
extern Widget filelist1;
extern Widget savefile1;
extern Widget saveok_fr;
extern Widget savecancel_fr;

extern void create_helpWin ();

extern void create_restoreWin ();

extern void create_saveWin ();

extern void create_serverDialog ();

extern void create_shell1 ();


extern void create_Long ();

extern void create_save_win ();

extern void create_signal_Sel ();

extern void create_help_win ();

extern void create_frame_win ();


#endif
