! Generated by WorkShop Visual


! errorDialog

! messageBox2

! errorDialogMessage


! helpWin

! messageBox1

! label44
DataViewer*MessageLabel.labelString: aLIGO DataViewer 2.8.4\nJuly 8th, 2014


! restoreWin

! fileSelect2

! button174
DataViewer*OK.labelString: OK

! restorefile


! saveWin

! fileSelect1

! button172
DataViewer*OK.labelString: OK

! savefile


! shell1
DataViewer.mwmMenu: \n
DataViewer.inputMethod: ()
DataViewer.iconName: dataviewer

! form1

! menuTop

! mainTop

! MainMenu

! saveSets

! restoreSets

! exitall

! framesTop

! menu16

! maketoc

! opentoc

! frameFile

! helpTop

! helpMenu

! helpItem1

! cascade8

! StatusForm

! statusField

! actionText

! tabBook
DataViewer*tabBook.autoManage: true

! bulletin2

! button165

! button166

! button178

! button179

! button180

! inputForm
DataViewer*inputForm.anchorChild: 0

! connectButton

! label63

! serverIpText
DataViewer*serverIpText.columns: 40

! serverPortText

! label31

! label18

! displayForm

! label20

! form27

! plotDisplay
DataViewer*plotDisplay.columns: 20

! newDisplayButton

! radioBox5

! xmgraceToggle
DataViewer*xmgraceToggle.indicatorType: ONE_OF_MANY

! toggle65
DataViewer*toggle65.indicatorType: ONE_OF_MANY

! label64

! sig_form

! junk

! chincr

! chdecr

! sigselect

! selchan

! sigcancel

! fastslowch
DataViewer*fastslowch.entryAlignment: ALIGNMENT_CENTER

! sfast

! sslow

! sdmt

! sobsole

! scrolledList2
DataViewer*grouplistSW.scrollBarPlacement: BOTTOM_RIGHT

! grouplist
DataViewer*grouplist.itemCount: 1
DataViewer*grouplist.items: 

! siglist

! label50

! selsig

! realTimeForm

! trigFrame

! trigForm

! trigOn

! trChMenu

! label74

! trigMenu

! trig1

! trig2

! trig3

! trig4

! trig5

! trig6

! trig7

! trig8

! trig9

! trig10

! trig11

! trig12

! trig13

! trig14

! trig15

! trig16

! trigLevelText

! aboveMenu

! trigaboveMenu

! above

! below

! label53

! midFrame

! midForm

! menuColor

! label46

! menuColorText

! colormenu

! red

! green

! blue

! yellow

! brown

! violet

! cyan

! magenta

! orange

! indigo

! maroon

! turqse

! green4

! alldef

! xAxisFrame

! label57

! menuDelay

! label47

! menuDelayText

! delayMenu

! a0

! a1

! a2

! a3

! a4

! a5

! a6

! a7

! a8

! a9

! a10

! a11

! a12

! a13

! a14

! a15

! menuXScale

! label48

! menuXScaleText

! xAxisMenu

! xAxisN16

! xAxisN8

! xAxisN4

! xAxisN2

! xAxis1

! xAxis2

! xAxis4

! xAxis8

! xAxis16

! yAxisFrame

! label58

! yscaleForm

! ymaxLabel
DataViewer*ymaxLabel.alignment: ALIGNMENT_END

! yminLabel
DataViewer*yminLabel.alignment: ALIGNMENT_END

! yMaxText

! yMinText

! unitOn

! autoOn

! menuYScale

! label49

! menuYScaleText

! yScaleMenu

! linearsel

! expsel

! logsel

! lnsel

! menuChan

! label52

! menuChanText

! chMenu

! win1

! win2

! win3

! win4

! win5

! win6

! win7

! win8

! win9

! win10

! win11

! win12

! win13

! win14

! win15

! win16

! sigNamText
DataViewer*sigNamText.recomputeSize: false

! slotsFrame

! label54

! rowcol4

! ch1Select
DataViewer*ch1Select.indicatorType: N_OF_MANY
DataViewer*ch1Select.set: false

! ch2Select
DataViewer*ch2Select.indicatorType: N_OF_MANY
DataViewer*ch2Select.set: false

! ch3Select
DataViewer*ch3Select.indicatorType: N_OF_MANY

! ch4Select
DataViewer*ch4Select.indicatorType: N_OF_MANY

! ch5Select
DataViewer*ch5Select.indicatorType: N_OF_MANY

! ch6Select
DataViewer*ch6Select.indicatorType: N_OF_MANY

! ch7Select
DataViewer*ch7Select.indicatorType: N_OF_MANY

! ch8Select
DataViewer*ch8Select.indicatorType: N_OF_MANY

! ch9Select

! ch10Select

! ch11Select

! ch12Select

! ch13Select

! ch14Select

! ch15Select

! ch16Select

! modeForm

! displayType

! label19

! displayTypeText

! opMenu

! timebase

! trmean

! menuMode

! label21

! menuModeText

! modeMenu

! stand

! multi

! menuRes

! label22

! menuResText

! reMenu

! dr1

! dr2

! dr4

! dr8

! dr16

! dr32

! dr64

! dr128

! menuRate

! label23

! menuRateText

! rateMenu

! freq1

! freq2

! freq4

! freq8

! freq16

! sigOn

! filterOn

! globalOn

! buttonForm

! stopbtn

! playbtn

! Longf

! lchann

! longch

! lch1
DataViewer*lch1.indicatorType: N_OF_MANY
DataViewer*lch1.set: true

! lch2
DataViewer*lch2.indicatorType: N_OF_MANY
DataViewer*lch2.set: true

! lch3
DataViewer*lch3.indicatorType: N_OF_MANY
DataViewer*lch3.set: false

! lch4
DataViewer*lch4.indicatorType: N_OF_MANY

! lch5
DataViewer*lch5.indicatorType: N_OF_MANY

! lch6
DataViewer*lch6.indicatorType: N_OF_MANY

! lch7
DataViewer*lch7.indicatorType: N_OF_MANY

! lch8
DataViewer*lch8.indicatorType: N_OF_MANY

! lch9

! lch10

! lch11

! lch12

! lch13

! lch14

! lch15

! lch16

! label38

! lmode

! radioBox6

! lstand
DataViewer*lstand.set: false

! lmult

! multixmgr

! label55

! autoset

! styleMenu

! label26

! style

! stdefault

! stline

! stpoint

! bogus

! label62
DataViewer*label62.labelString: Stop

! lidtext

! stopid

! label61

! menu_operation

! trigandor

! and

! or

! trigLevelText2

! menuAbove2

! trigAboveLong2

! above2

! below2

! eqa2

! manuChtrig2

! trigMenu2

! button144

! button145

! button146

! button147

! button148

! button149

! button150

! button151

! button152

! button153

! button154

! button155

! button156

! button157

! button158

! button159

! trigLevelText1

! menuAbove1

! trigAboveLong1

! above1

! below1

! equ1

! menuChtrig1

! trigMenu1

! button128

! button129

! button130

! button131

! button132

! button133

! button134

! button135

! button136

! button137

! button138

! button139

! button140

! button141

! button142

! button143

! longTrigExe

! serverset

! lserver
DataViewer*lserver.set: true

! lframe

! label59

! lIPtext

! lPorttext

! startLong

! stopPlaybackButton

! label7

! lmin
DataViewer*lmin.set: true

! lmax
DataViewer*lmax.set: true

! lrms
DataViewer*lrms.set: true

! ygrid
DataViewer*ygrid.set: true

! xgrid
DataViewer*xgrid.set: true

! label8

! button125

! button126

! timeNow
DataViewer*timeNow.armColor: MidnightBlue

! timeForm1

! label15

! playSc

! refTimeSec

! label16

! gpstime

! gpsref

! label14

! playMn

! refTimeMin

! label13

! playHr

! refTimeHr

! label11

! playDa

! refTimeDay

! label10

! playMo

! label9

! playYr

! label17

! timeset

! radiotime

! lutc

! lgps

! label60

! fbMenu

! label93

! menu23

! stoptime

! starttime

! label6

! ldec

! radioBox3

! lfull
DataViewer*lfull.set: false

! lsec

! lmin1

! lmin10

! lhr

! label56

! v1

! v2

! v3

! v4

! v5

! v6

! v7

! v8

! v9

! v10

! v11

! v12

! v13

! v14

! v15

! v16


! frame_win

! framefile_form

! label24

! label25

! dirlist1
DataViewer*dirlist1.itemCount: 1
DataViewer*dirlist1.items: 

! filelist1

! label29

! savefile1

! saveok_fr

! savecancel_fr

! label28

