#!/bin/bash
#
# Uninstall one system

if [ "$#" -ne 2 ];then
	echo "pls state the name of the system to uninstall and the source code directory";
	exit 1;
else
	system=$1;
	srcdir=$2;
fi

upper_system=`echo $system | tr a-z A-Z`
site=`grep site= target/${system}epics/${system}epics*.cmd | sed 's/.*site=\([a-z]*\).*/\1/g'`
if test ${site}no = no; then echo Please make $system first; exit 1; fi
upper_site=`echo $site | tr a-z A-Z`
site_letter=M
if test ${site} = llo; then site_letter=L; fi
if test ${site} = lho; then site_letter=H; fi
if test ${site} = geo; then site_letter=G; fi
if test ${site} = caltech; then site_letter=C; fi
if test ${site} = tst; then site_letter=X; fi
if test ${site} = stn; then site_letter=S; fi
if test ${site} = kamioka; then site_letter=K; fi
if test ${site} = indigo; then site_letter=I; fi
if test ${site} = anu; then site_letter=A; fi
if test ${site} = uwa; then site_letter=U; fi
if test ${site} = cardiff; then site_letter=W; fi
if test ${site} = bham; then site_letter=B; fi
ifo=`grep ifo= target/${system}epics/${system}epics*.cmd | head -1 | sed 's/.*ifo=\([a-zA-Z0-9]*\).*/\1/g'`
gds_node=`grep rmid build/${system}epics/${system}.par | head -1| sed 's/[^0-9]*\([0-9]*\)/\1/'`
datarate=`grep datarate build/${system}epics/${system}.par | head -1| sed 's/[^0-9]*\([0-9]*\)/\1/'`
lower_ifo=`echo $ifo | tr A-Z a-z`
cur_date=`date +%y%m%d_%H%M%S`
echo Removing GDS node ${gds_node} configuration file 
echo /opt/rtcds/${site}/target/gds/param/tpchn_${system}.par
/bin/rm -f  /opt/rtcds/${site}/target/gds/param/tpchn_${system}.par
echo Removing DAQ configuration file
echo /opt/rtcds/${site}/${lower_ifo}/chans/daq/${upper_system}.ini
