#!/bin/bash
# dolphin_wait - Wait until the number of dead dolphin nodes is 0

# get ports for dxadmin call - chunks are host, node port, server port, front-end port
PORTCFG=`/etc/dxportcfg.sh`
DXHOST=`echo $PORTCFG | awk '{print $1}'`
SVRPORT=`echo $PORTCFG | awk '{print $3}'`
FEPORT=`echo $PORTCFG | awk '{print $4}'`
echo Dolphin wait host $DXHOST serverport $SVRPORT feport $FEPORT
function ndead_dolphin_nodes {
 res=`/opt/DIS/sbin/dxadmin_commandline -fabric 0 -cluster $DXHOST -portserver $SVRPORT -portfrontend $FEPORT get-cluster | grep nbr-dead-nodes | awk '{print $(NF)}'`
 if [ -z $res ]; then
    echo 999
 else
    echo $res;
 fi
}
ndead=$(ndead_dolphin_nodes);
while [ $ndead -gt 0 ]
do
echo $ndead dead Dolphin nodes in fabric, waiting...
sleep 2;
ndead=$(ndead_dolphin_nodes)
done
