#!/bin/bash
# dolphin_ix_wait - Wait until the number of dead dolphin IX nodes is 0
# Updated for Dolphin release 4.4.1 - search for "Number of unreachable nodes"

# get ports for dxadmin call - chunks are host, node port, server port, front-end port
PORTCFG=`/etc/ixportcfg.sh`
IXHOST=`echo $PORTCFG | awk '{print $1}'`
SVRPORT=`echo $PORTCFG | awk '{print $3}'`
FEPORT=`echo $PORTCFG | awk '{print $4}'`
echo Dolphin wait host $IXHOST serverport $SVRPORT feport $FEPORT
function ndead_dolphin_nodes {
 res=`/opt/DIS-IX/sbin/ixadmin_commandline -fabric 0 -cluster $IXHOST -portserver $SVRPORT -portfrontend $FEPORT get-cluster-info | grep unreachable | awk '{print $(NF)}'`
 if [ -z $res ]; then
    echo 999
 else
    echo $res;
 fi
}
ndead=$(ndead_dolphin_nodes);
while [ $ndead -gt 0 ]
do
echo $ndead dead Dolphin IX nodes in fabric, waiting...
sleep 2;
ndead=$(ndead_dolphin_nodes)
done
