support/bin/rts_awgtpman_exec usr/bin
support/bin/rts_epics_exec usr/bin
support/bin/rts_module_ctrl usr/bin
support/systemd/rts-awgtpman@.service lib/systemd/system
support/systemd/rts-edc.service lib/systemd/system
support/systemd/rts-epics@.service lib/systemd/system
support/systemd/rts-local_dc.service lib/systemd/system
support/systemd/rts-module@.service lib/systemd/system
support/systemd/rts@.target lib/systemd/system
usr/bin/awgtpman
usr/bin/local_dc
usr/bin/standalone_edc
