
# Define Epics system name. It should be unique.
TARGET = hepiepics

SRC = build/$(TARGET)/hepi.st

SRC += src/drv/rfm.c
SRC += src/drv/param.c
SRC += src/drv/crc.c
SRC += src/drv/fmReadCoeff.c

DB += build/$(TARGET)/hepi1.db

IFO = M1
SITE = mit

SEQ += 'hepi,("ifo=M1, site=mit, sys=SEI, sysnum= 21")'

CFLAGS += -DHEPI_CODE -DFIR_FILTERS

include config/Makefile.linux

build/$(TARGET)/hepi1.db: build/$(TARGET)/hepi.db
	sed 's/%SYS%/SEI/g;s/%SUBSYS%//g' $< > $@


