#!/bin/sh
if [ $UID != 0 ]; then SUDO="sudo "; else SUDO=""; fi
echo
echo "*** Simple RTAI SHM demo (kernel) ***"
echo "Press <enter> to load modules:"
read junk
cd ..; sudo ./ldmod; cd -
echo
echo "Now start the realtime process <enter>, <ctrl-C> to end it."
read junk
sync
sudo /sbin/insmod ./setup_shmem.ko;
#./display
echo
echo "Done. Press <enter> to remove the modules."
read junk
./rem
