/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gdsrsched.h"

#ifndef SIG_PF
#define	SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define	RPC_SVC_FG
#endif

#define	_RPCSVC_CLOSEDOWN 120
#define		_RPC_SVC
#include "dtt/rpcinc.h"
extern int _rpcpmstart;		/* Started by a port monitor ? */

/* States a server can be in wrt request */

#define	_IDLE 0
#define	_SERVED 1

static int _rpcsvcstate = _IDLE;	/* Set when a request is serviced */
static int _rpcsvccount = 0;		/* Number of requests being serviced */
mutex_t _svcstate_lock;			/* lock for _rpcsvcstate, _rpcsvccount */

static
void _msgout(char* msg)
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, msg);
#endif
}

int
_closescheduler_1(closescheduler_1_argument *argp, int *result, struct svc_req *rqstp)
{
	return (closescheduler_1_svc(argp->sd, argp->timeout, result, rqstp));
}

int
_scheduletask_1(scheduletask_1_argument *argp, int *result, struct svc_req *rqstp)
{
	return (scheduletask_1_svc(argp->sd, argp->newtask, result, rqstp));
}

int
_getscheduledtask_1(getscheduledtask_1_argument *argp, resultGetScheduledTask_r *result, struct svc_req *rqstp)
{
	return (getscheduledtask_1_svc(argp->sd, argp->id, result, rqstp));
}

int
_removescheduledtask_1(removescheduledtask_1_argument *argp, int *result, struct svc_req *rqstp)
{
	return (removescheduledtask_1_svc(argp->sd, argp->id, argp->terminate, result, rqstp));
}

int
_waitforschedulertofinish_1(waitforschedulertofinish_1_argument *argp, int *result, struct svc_req *rqstp)
{
	return (waitforschedulertofinish_1_svc(argp->sd, argp->timeout, result, rqstp));
}

int
_settagnotify_1(settagnotify_1_argument *argp, int *result, struct svc_req *rqstp)
{
	return (settagnotify_1_svc(argp->sd, argp->tag, argp->time, result, rqstp));
}

int
_connectscheduler_1(connectscheduler_1_argument *argp, remotesched_r *result, struct svc_req *rqstp)
{
	return (connectscheduler_1_svc(argp->callbacksd, argp->callbackprogram, argp->callbackversion, result, rqstp));
}

int
_settagcallback_1(settagcallback_1_argument *argp, int *result, struct svc_req *rqstp)
{
	return (settagcallback_1_svc(argp->sd, argp->bsd, argp->tag, argp->time, result, rqstp));
}

void
gdsscheduler_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		closescheduler_1_argument closescheduler_1_arg;
		scheduletask_1_argument scheduletask_1_arg;
		getscheduledtask_1_argument getscheduledtask_1_arg;
		removescheduledtask_1_argument removescheduledtask_1_arg;
		waitforschedulertofinish_1_argument waitforschedulertofinish_1_arg;
		settagnotify_1_argument settagnotify_1_arg;
		connectscheduler_1_argument connectscheduler_1_arg;
	} argument;
	union {
		int closescheduler_1_res;
		int scheduletask_1_res;
		resultGetScheduledTask_r getscheduledtask_1_res;
		int removescheduledtask_1_res;
		int waitforschedulertofinish_1_res;
		int settagnotify_1_res;
		remotesched_r connectscheduler_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	mutex_lock(&_svcstate_lock);
	_rpcsvccount++;
	mutex_unlock(&_svcstate_lock);
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp,
			(xdrproc_t) xdr_void, (char *)NULL);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;

	case CLOSESCHEDULER:
		_xdr_argument = (xdrproc_t) xdr_closescheduler_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_closescheduler_1;
		break;

	case SCHEDULETASK:
		_xdr_argument = (xdrproc_t) xdr_scheduletask_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_scheduletask_1;
		break;

	case GETSCHEDULEDTASK:
		_xdr_argument = (xdrproc_t) xdr_getscheduledtask_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultGetScheduledTask_r;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_getscheduledtask_1;
		break;

	case REMOVESCHEDULEDTASK:
		_xdr_argument = (xdrproc_t) xdr_removescheduledtask_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_removescheduledtask_1;
		break;

	case WAITFORSCHEDULERTOFINISH:
		_xdr_argument = (xdrproc_t) xdr_waitforschedulertofinish_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_waitforschedulertofinish_1;
		break;

	case SETTAGNOTIFY:
		_xdr_argument = (xdrproc_t) xdr_settagnotify_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_settagnotify_1;
		break;

	case CONNECTSCHEDULER:
		_xdr_argument = (xdrproc_t) xdr_connectscheduler_1_argument;
		_xdr_result = (xdrproc_t) xdr_remotesched_r;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_connectscheduler_1;
		break;

	default:
		svcerr_noproc(transp);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, _xdr_result, (char *)&result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	if (!gdsscheduler_1_freeresult(transp, _xdr_result, (caddr_t) &result))
		_msgout("unable to free results");

	mutex_lock(&_svcstate_lock);
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	mutex_unlock(&_svcstate_lock);
	return;
}

void
gdsschedulercallback_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		settagcallback_1_argument settagcallback_1_arg;
	} argument;
	union {
		int settagcallback_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	mutex_lock(&_svcstate_lock);
	_rpcsvccount++;
	mutex_unlock(&_svcstate_lock);
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp,
			(xdrproc_t) xdr_void, (char *)NULL);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;

	case SETTAGCALLBACK:
		_xdr_argument = (xdrproc_t) xdr_settagcallback_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *,  void *,  struct svc_req *))_settagcallback_1;
		break;

	default:
		svcerr_noproc(transp);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		mutex_lock(&_svcstate_lock);
		_rpcsvccount--;
		_rpcsvcstate = _SERVED;
		mutex_unlock(&_svcstate_lock);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, _xdr_result, (char *)&result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, _xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	if (!gdsschedulercallback_1_freeresult(transp, _xdr_result, (caddr_t) &result))
		_msgout("unable to free results");

	mutex_lock(&_svcstate_lock);
	_rpcsvccount--;
	_rpcsvcstate = _SERVED;
	mutex_unlock(&_svcstate_lock);
	return;
}
