/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rawgapi.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#define _RPC_SVC
#include "dtt/rpcinc.h"

int
_awgnewchannel_1 (awgnewchannel_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgnewchannel_1_svc(argp->chntype, argp->id, argp->arg1, argp->arg2, result, rqstp));
}

int
_awgremovechannel_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (awgremovechannel_1_svc(*argp, result, rqstp));
}

int
_awgaddwaveform_1 (awgaddwaveform_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgaddwaveform_1_svc(argp->slot, argp->comps, result, rqstp));
}

int
_awgsetwaveform_1 (awgsetwaveform_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgsetwaveform_1_svc(argp->slot, argp->wave, result, rqstp));
}

int
_awgsendwaveform_1 (awgsendwaveform_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgsendwaveform_1_svc(argp->slot, argp->time, argp->epoch, argp->wave, result, rqstp));
}

int
_awgstopwaveform_1 (awgstopwaveform_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgstopwaveform_1_svc(argp->slot, argp->terminate, argp->tArg, result, rqstp));
}

int
_awgsetgain_1 (awgsetgain_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgsetgain_1_svc(argp->slot, argp->gain, argp->tArg, result, rqstp));
}

int
_awgclearwaveforms_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (awgclearwaveforms_1_svc(*argp, result, rqstp));
}

int
_awgquerywaveforms_1 (awgquerywaveforms_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgquerywaveforms_1_svc(argp->slot, argp->maxComp, result, rqstp));
}

int
_awgreset_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (awgreset_1_svc(result, rqstp));
}

int
_awgsetfilter_1 (awgsetfilter_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (awgsetfilter_1_svc(argp->slot, argp->filter, result, rqstp));
}

int
_awgstatistics_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (awgstatistics_1_svc(*argp, result, rqstp));
}

int
_awgshow_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (awgshow_1_svc(result, rqstp));
}

int
_awgshowslot_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (awgshowslot_1_svc(*argp, result, rqstp));
}

void
rawgprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		awgnewchannel_1_argument awgnewchannel_1_arg;
		int awgremovechannel_1_arg;
		awgaddwaveform_1_argument awgaddwaveform_1_arg;
		awgsetwaveform_1_argument awgsetwaveform_1_arg;
		awgsendwaveform_1_argument awgsendwaveform_1_arg;
		awgstopwaveform_1_argument awgstopwaveform_1_arg;
		awgsetgain_1_argument awgsetgain_1_arg;
		int awgclearwaveforms_1_arg;
		awgquerywaveforms_1_argument awgquerywaveforms_1_arg;
		awgsetfilter_1_argument awgsetfilter_1_arg;
		int awgstatistics_1_arg;
		int awgshowslot_1_arg;
	} argument;
	union {
		int awgnewchannel_1_res;
		int awgremovechannel_1_res;
		int awgaddwaveform_1_res;
		int awgsetwaveform_1_res;
		int awgsendwaveform_1_res;
		int awgstopwaveform_1_res;
		int awgsetgain_1_res;
		int awgclearwaveforms_1_res;
		awgquerywaveforms_r awgquerywaveforms_1_res;
		int awgreset_1_res;
		int awgsetfilter_1_res;
		awgstat_r awgstatistics_1_res;
		awgshow_r awgshow_1_res;
		awgshow_r awgshowslot_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case AWGNEWCHANNEL:
		_xdr_argument = (xdrproc_t) xdr_awgnewchannel_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgnewchannel_1;
		break;

	case AWGREMOVECHANNEL:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgremovechannel_1;
		break;

	case AWGADDWAVEFORM:
		_xdr_argument = (xdrproc_t) xdr_awgaddwaveform_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgaddwaveform_1;
		break;

	case AWGSETWAVEFORM:
		_xdr_argument = (xdrproc_t) xdr_awgsetwaveform_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgsetwaveform_1;
		break;

	case AWGSENDWAVEFORM:
		_xdr_argument = (xdrproc_t) xdr_awgsendwaveform_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgsendwaveform_1;
		break;

	case AWGSTOPWAVEFORM:
		_xdr_argument = (xdrproc_t) xdr_awgstopwaveform_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgstopwaveform_1;
		break;

	case AWGSETGAIN:
		_xdr_argument = (xdrproc_t) xdr_awgsetgain_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgsetgain_1;
		break;

	case AWGCLEARWAVEFORMS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgclearwaveforms_1;
		break;

	case AWGQUERYWAVEFORMS:
		_xdr_argument = (xdrproc_t) xdr_awgquerywaveforms_1_argument;
		_xdr_result = (xdrproc_t) xdr_awgquerywaveforms_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgquerywaveforms_1;
		break;

	case AWGRESET:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgreset_1;
		break;

	case AWGSETFILTER:
		_xdr_argument = (xdrproc_t) xdr_awgsetfilter_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgsetfilter_1;
		break;

	case AWGSTATISTICS:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_awgstat_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgstatistics_1;
		break;

	case AWGSHOW:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_awgshow_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgshow_1;
		break;

	case AWGSHOWSLOT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_awgshow_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_awgshowslot_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rawgprog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
