/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rawgapi.h"
#define _RPC_CLNT
#include "dtt/rpcinc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
awgnewchannel_1(int chntype, int id, int arg1, int arg2, int *clnt_res,  CLIENT *clnt)
{
	awgnewchannel_1_argument arg;
	arg.chntype = chntype;
	arg.id = id;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, AWGNEWCHANNEL, (xdrproc_t) xdr_awgnewchannel_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgremovechannel_1(int slot, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, AWGREMOVECHANNEL,
		(xdrproc_t) xdr_int, (caddr_t) &slot,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgaddwaveform_1(int slot, awgcomponent_list_r comps, int *clnt_res,  CLIENT *clnt)
{
	awgaddwaveform_1_argument arg;
	arg.slot = slot;
	arg.comps = comps;
	return (clnt_call (clnt, AWGADDWAVEFORM, (xdrproc_t) xdr_awgaddwaveform_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgsetwaveform_1(int slot, awgwaveform_r wave, int *clnt_res,  CLIENT *clnt)
{
	awgsetwaveform_1_argument arg;
	arg.slot = slot;
	arg.wave = wave;
	return (clnt_call (clnt, AWGSETWAVEFORM, (xdrproc_t) xdr_awgsetwaveform_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgsendwaveform_1(int slot, u_int time, int epoch, awgwaveform_r wave, int *clnt_res,  CLIENT *clnt)
{
	awgsendwaveform_1_argument arg;
	arg.slot = slot;
	arg.time = time;
	arg.epoch = epoch;
	arg.wave = wave;
	return (clnt_call (clnt, AWGSENDWAVEFORM, (xdrproc_t) xdr_awgsendwaveform_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgstopwaveform_1(int slot, int terminate, quad_t tArg, int *clnt_res,  CLIENT *clnt)
{
	awgstopwaveform_1_argument arg;
	arg.slot = slot;
	arg.terminate = terminate;
	arg.tArg = tArg;
	return (clnt_call (clnt, AWGSTOPWAVEFORM, (xdrproc_t) xdr_awgstopwaveform_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgsetgain_1(int slot, double gain, quad_t tArg, int *clnt_res,  CLIENT *clnt)
{
	awgsetgain_1_argument arg;
	arg.slot = slot;
	arg.gain = gain;
	arg.tArg = tArg;
	return (clnt_call (clnt, AWGSETGAIN, (xdrproc_t) xdr_awgsetgain_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgclearwaveforms_1(int slot, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, AWGCLEARWAVEFORMS,
		(xdrproc_t) xdr_int, (caddr_t) &slot,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgquerywaveforms_1(int slot, int maxComp, awgquerywaveforms_r *clnt_res,  CLIENT *clnt)
{
	awgquerywaveforms_1_argument arg;
	arg.slot = slot;
	arg.maxComp = maxComp;
	return (clnt_call (clnt, AWGQUERYWAVEFORMS, (xdrproc_t) xdr_awgquerywaveforms_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_awgquerywaveforms_r, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgreset_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, AWGRESET, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
awgsetfilter_1(int slot, awgfilter_r filter, int *clnt_res,  CLIENT *clnt)
{
	awgsetfilter_1_argument arg;
	arg.slot = slot;
	arg.filter = filter;
	return (clnt_call (clnt, AWGSETFILTER, (xdrproc_t) xdr_awgsetfilter_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgstatistics_1(int reset, awgstat_r *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, AWGSTATISTICS,
		(xdrproc_t) xdr_int, (caddr_t) &reset,
		(xdrproc_t) xdr_awgstat_r, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
awgshow_1(awgshow_r *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, AWGSHOW, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_awgshow_r, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
awgshowslot_1(int slot, awgshow_r *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, AWGSHOWSLOT,
		(xdrproc_t) xdr_int, (caddr_t) &slot,
		(xdrproc_t) xdr_awgshow_r, (caddr_t) clnt_res,
		TIMEOUT));
}
