/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rawgapi.h"
#define _RPC_XDR
#include "dtt/rpcinc.h"

bool_t
xdr_awgcomponent_r (XDR *xdrs, awgcomponent_r *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->wtype))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->ramptype))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->par, 4,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->start))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->duration))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->restart))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ramptime, 2,
		sizeof (quad_t), (xdrproc_t) xdr_quad_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ramppar, 4,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgcomponent_list_r (XDR *xdrs, awgcomponent_list_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->awgcomponent_list_r_val, (u_int *) &objp->awgcomponent_list_r_len, ~0,
		sizeof (awgcomponent_r), (xdrproc_t) xdr_awgcomponent_r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgwaveform_r (XDR *xdrs, awgwaveform_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->awgwaveform_r_val, (u_int *) &objp->awgwaveform_r_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgfilter_r (XDR *xdrs, awgfilter_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->awgfilter_r_val, (u_int *) &objp->awgfilter_r_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgquerywaveforms_r (XDR *xdrs, awgquerywaveforms_r *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_awgcomponent_list_r (xdrs, &objp->wforms))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgshow_r (XDR *xdrs, awgshow_r *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->res, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgstat_r (XDR *xdrs, awgstat_r *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->pwNum))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->pwMean))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->pwStddev))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->pwMax))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rmNum))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rmMean))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rmStddev))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rmMax))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rmCrit))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->rmNumCrit))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dcNum))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dcMean))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dcStddev))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dcMax))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->dcNumCrit))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgnewchannel_1_argument (XDR *xdrs, awgnewchannel_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->chntype))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgaddwaveform_1_argument (XDR *xdrs, awgaddwaveform_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_awgcomponent_list_r (xdrs, &objp->comps))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgsetwaveform_1_argument (XDR *xdrs, awgsetwaveform_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_awgwaveform_r (xdrs, &objp->wave))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgsendwaveform_1_argument (XDR *xdrs, awgsendwaveform_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->time))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->epoch))
		 return FALSE;
	 if (!xdr_awgwaveform_r (xdrs, &objp->wave))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgstopwaveform_1_argument (XDR *xdrs, awgstopwaveform_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->terminate))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->tArg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgsetgain_1_argument (XDR *xdrs, awgsetgain_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->gain))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->tArg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgquerywaveforms_1_argument (XDR *xdrs, awgquerywaveforms_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->maxComp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_awgsetfilter_1_argument (XDR *xdrs, awgsetfilter_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->slot))
		 return FALSE;
	 if (!xdr_awgfilter_r (xdrs, &objp->filter))
		 return FALSE;
	return TRUE;
}
