/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rchannel.h"
#define _RPC_CLNT
#include "dtt/rpcinc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
chnquery_1(resultChannelQuery_r *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, CHNQUERY, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_resultChannelQuery_r, (caddr_t) clnt_res,
		TIMEOUT));

}
