/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rchannel.h"
#define _RPC_XDR
#include "dtt/rpcinc.h"

bool_t
xdr_channelinfo_r (XDR *xdrs, channelinfo_r *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->chName, 40,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 8 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_short (xdrs, &objp->ifoId))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->rmId))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->dcuId))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->chNum))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->dataType))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dataRate))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->chGroup))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->bps))
				 return FALSE;

		} else {
		IXDR_PUT_SHORT(buf, objp->ifoId);
		IXDR_PUT_SHORT(buf, objp->rmId);
		IXDR_PUT_SHORT(buf, objp->dcuId);
		IXDR_PUT_SHORT(buf, objp->chNum);
		IXDR_PUT_SHORT(buf, objp->dataType);
		IXDR_PUT_LONG(buf, objp->dataRate);
		IXDR_PUT_SHORT(buf, objp->chGroup);
		IXDR_PUT_SHORT(buf, objp->bps);
		}
		 if (!xdr_float (xdrs, &objp->gain))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->slope))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->offset))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->unit, 40,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_u_long (xdrs, &objp->rmOffset))
			 return FALSE;
		 if (!xdr_u_long (xdrs, &objp->rmBlockSize))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->chName, 40,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 8 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_short (xdrs, &objp->ifoId))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->rmId))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->dcuId))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->chNum))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->dataType))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->dataRate))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->chGroup))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->bps))
				 return FALSE;

		} else {
		objp->ifoId = IXDR_GET_SHORT(buf);
		objp->rmId = IXDR_GET_SHORT(buf);
		objp->dcuId = IXDR_GET_SHORT(buf);
		objp->chNum = IXDR_GET_SHORT(buf);
		objp->dataType = IXDR_GET_SHORT(buf);
		objp->dataRate = IXDR_GET_LONG(buf);
		objp->chGroup = IXDR_GET_SHORT(buf);
		objp->bps = IXDR_GET_SHORT(buf);
		}
		 if (!xdr_float (xdrs, &objp->gain))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->slope))
			 return FALSE;
		 if (!xdr_float (xdrs, &objp->offset))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->unit, 40,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_u_long (xdrs, &objp->rmOffset))
			 return FALSE;
		 if (!xdr_u_long (xdrs, &objp->rmBlockSize))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->chName, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->ifoId))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->rmId))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dcuId))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->chNum))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->dataType))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dataRate))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->chGroup))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->bps))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->gain))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->slope))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->unit, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->rmOffset))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->rmBlockSize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_channellist_r (XDR *xdrs, channellist_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->channellist_r_val, (u_int *) &objp->channellist_r_len, ~0,
		sizeof (channelinfo_r), (xdrproc_t) xdr_channelinfo_r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultChannelQuery_r (XDR *xdrs, resultChannelQuery_r *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_channellist_r (xdrs, &objp->chnlist))
		 return FALSE;
	return TRUE;
}
