/* Version: $Id$ */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RLAUNCH_H_RPCGEN
#define _RLAUNCH_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define _RPC_HDR
#include "dtt/rpcinc.h"

struct launch_info_r {
	char *title;
	char *prog;
};
typedef struct launch_info_r launch_info_r;

typedef struct {
	u_int launch_infolist_r_len;
	launch_info_r *launch_infolist_r_val;
} launch_infolist_r;

struct resultLaunchInfoQuery_r {
	int status;
	launch_infolist_r list;
};
typedef struct resultLaunchInfoQuery_r resultLaunchInfoQuery_r;

struct launch_1_argument {
	char *category;
	char *prog;
	char *display;
};
typedef struct launch_1_argument launch_1_argument;

#define RLAUNCHPROG 0x31001007
#define RLAUCNHVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define LAUNCHQUERY 1
extern  enum clnt_stat launchquery_1(resultLaunchInfoQuery_r *, CLIENT *);
extern  bool_t launchquery_1_svc(resultLaunchInfoQuery_r *, struct svc_req *);
#define LAUNCH 2
extern  enum clnt_stat launch_1(char *, char *, char *, int *, CLIENT *);
extern  bool_t launch_1_svc(char *, char *, char *, int *, struct svc_req *);
extern int rlaunchprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LAUNCHQUERY 1
extern  enum clnt_stat launchquery_1();
extern  bool_t launchquery_1_svc();
#define LAUNCH 2
extern  enum clnt_stat launch_1();
extern  bool_t launch_1_svc();
extern int rlaunchprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_launch_info_r (XDR *, launch_info_r*);
extern  bool_t xdr_launch_infolist_r (XDR *, launch_infolist_r*);
extern  bool_t xdr_resultLaunchInfoQuery_r (XDR *, resultLaunchInfoQuery_r*);
extern  bool_t xdr_launch_1_argument (XDR *, launch_1_argument*);

#else /* K&R C */
extern bool_t xdr_launch_info_r ();
extern bool_t xdr_launch_infolist_r ();
extern bool_t xdr_resultLaunchInfoQuery_r ();
extern bool_t xdr_launch_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RLAUNCH_H_RPCGEN */
