/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rlaunch.h"
#define _RPC_CLNT
#include "dtt/rpcinc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
launchquery_1(resultLaunchInfoQuery_r *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, LAUNCHQUERY, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_resultLaunchInfoQuery_r, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
launch_1(char *category, char *prog, char *display, int *clnt_res,  CLIENT *clnt)
{
	launch_1_argument arg;
	arg.category = category;
	arg.prog = prog;
	arg.display = display;
	return (clnt_call (clnt, LAUNCH, (xdrproc_t) xdr_launch_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
