/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rleap.h"
#define _RPC_XDR
#include "dtt/rpcinc.h"

bool_t
xdr_leap_r (XDR *xdrs, leap_r *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->transition))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->change))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_leaplist_r (XDR *xdrs, leaplist_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->leaplist_r_val, (u_int *) &objp->leaplist_r_len, ~0,
		sizeof (leap_r), (xdrproc_t) xdr_leap_r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultLeapQuery_r (XDR *xdrs, resultLeapQuery_r *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_leaplist_r (xdrs, &objp->leaplist))
		 return FALSE;
	return TRUE;
}
