/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rtestpoint.h"
#define _RPC_CLNT
#include "dtt/rpcinc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
requesttp_1(int id, int node, TP_r tp, quad_t timeout, resultRequestTP_r *clnt_res,  CLIENT *clnt)
{
	requesttp_1_argument arg;
	arg.id = id;
	arg.node = node;
	arg.tp = tp;
	arg.timeout = timeout;
	return (clnt_call (clnt, REQUESTTP, (xdrproc_t) xdr_requesttp_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultRequestTP_r, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
requesttpname_1(int id, char *tpnames, quad_t timeout, resultRequestTP_r *clnt_res,  CLIENT *clnt)
{
	requesttpname_1_argument arg;
	arg.id = id;
	arg.tpnames = tpnames;
	arg.timeout = timeout;
	return (clnt_call (clnt, REQUESTTPNAME, (xdrproc_t) xdr_requesttpname_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultRequestTP_r, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cleartp_1(int id, int node, TP_r TP, int *clnt_res,  CLIENT *clnt)
{
	cleartp_1_argument arg;
	arg.id = id;
	arg.node = node;
	arg.TP = TP;
	return (clnt_call (clnt, CLEARTP, (xdrproc_t) xdr_cleartp_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
cleartpname_1(int id, char *tpnames, int *clnt_res,  CLIENT *clnt)
{
	cleartpname_1_argument arg;
	arg.id = id;
	arg.tpnames = tpnames;
	return (clnt_call (clnt, CLEARTPNAME, (xdrproc_t) xdr_cleartpname_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
querytp_1(int id, int node, int tpinterface, int tplen, u_long time, int epoch, resultQueryTP_r *clnt_res,  CLIENT *clnt)
{
	querytp_1_argument arg;
	arg.id = id;
	arg.node = node;
	arg.tpinterface = tpinterface;
	arg.tplen = tplen;
	arg.time = time;
	arg.epoch = epoch;
	return (clnt_call (clnt, QUERYTP, (xdrproc_t) xdr_querytp_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_resultQueryTP_r, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
keepalive_1(int id, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, KEEPALIVE,
		(xdrproc_t) xdr_int, (caddr_t) &id,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
