/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rtestpoint.h"
#define _RPC_XDR
#include "dtt/rpcinc.h"

bool_t
xdr_TP_r (XDR *xdrs, TP_r *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->TP_r_val, (u_int *) &objp->TP_r_len, ~0,
		sizeof (u_int), (xdrproc_t) xdr_u_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultRequestTP_r (XDR *xdrs, resultRequestTP_r *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->time))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->epoch))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultQueryTP_r (XDR *xdrs, resultQueryTP_r *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_TP_r (xdrs, &objp->tp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_requesttp_1_argument (XDR *xdrs, requesttp_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	 if (!xdr_TP_r (xdrs, &objp->tp))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_requesttpname_1_argument (XDR *xdrs, requesttpname_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tpnames, ~0))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->timeout))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cleartp_1_argument (XDR *xdrs, cleartp_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	 if (!xdr_TP_r (xdrs, &objp->TP))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cleartpname_1_argument (XDR *xdrs, cleartpname_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->tpnames, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_querytp_1_argument (XDR *xdrs, querytp_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->node))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tpinterface))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tplen))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->time))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->epoch))
		 return FALSE;
	return TRUE;
}
