/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rtestpoint.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#define _RPC_SVC
#include "dtt/rpcinc.h"

int
_requesttp_1 (requesttp_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (requesttp_1_svc(argp->id, argp->node, argp->tp, argp->timeout, result, rqstp));
}

int
_requesttpname_1 (requesttpname_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (requesttpname_1_svc(argp->id, argp->tpnames, argp->timeout, result, rqstp));
}

int
_cleartp_1 (cleartp_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cleartp_1_svc(argp->id, argp->node, argp->TP, result, rqstp));
}

int
_cleartpname_1 (cleartpname_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (cleartpname_1_svc(argp->id, argp->tpnames, result, rqstp));
}

int
_querytp_1 (querytp_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (querytp_1_svc(argp->id, argp->node, argp->tpinterface, argp->tplen, argp->time, argp->epoch, result, rqstp));
}

int
_keepalive_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (keepalive_1_svc(*argp, result, rqstp));
}

void
rtestpoint_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		requesttp_1_argument requesttp_1_arg;
		requesttpname_1_argument requesttpname_1_arg;
		cleartp_1_argument cleartp_1_arg;
		cleartpname_1_argument cleartpname_1_arg;
		querytp_1_argument querytp_1_arg;
		int keepalive_1_arg;
	} argument;
	union {
		resultRequestTP_r requesttp_1_res;
		resultRequestTP_r requesttpname_1_res;
		int cleartp_1_res;
		int cleartpname_1_res;
		resultQueryTP_r querytp_1_res;
		int keepalive_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUESTTP:
		_xdr_argument = (xdrproc_t) xdr_requesttp_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultRequestTP_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_requesttp_1;
		break;

	case REQUESTTPNAME:
		_xdr_argument = (xdrproc_t) xdr_requesttpname_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultRequestTP_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_requesttpname_1;
		break;

	case CLEARTP:
		_xdr_argument = (xdrproc_t) xdr_cleartp_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cleartp_1;
		break;

	case CLEARTPNAME:
		_xdr_argument = (xdrproc_t) xdr_cleartpname_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_cleartpname_1;
		break;

	case QUERYTP:
		_xdr_argument = (xdrproc_t) xdr_querytp_1_argument;
		_xdr_result = (xdrproc_t) xdr_resultQueryTP_r;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_querytp_1;
		break;

	case KEEPALIVE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_keepalive_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!rtestpoint_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
